# Generated by Django 3.1.4 on 2021-01-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaBin',
            fields=[
                ('informacao_bin_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('issuer_name', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=40)),
                ('brand_name', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('is_international', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_token', models.BooleanField(default=False)),
            ],
        ),
    ]
